### ISSUE TITLE
Uncaught Error: Objects are not valid as a React child (found: object with keys {message, params, formatted})

### ISSUE THREAD

**Issue by Lms24** [getsentry/spotlight#360] opened 2024-02-15 09:39 UTC
_"Tested with current version of spotlight, and things seem much improved: the overlay no longer crashes when Sentry captures an error.  However, in some cases I am still seeing "Uncaught Error: Objects are not valid as a React child (found: object with keys {message, params, formatted}). If you meant to render a collection of children, use an array instead."  This error appears both in the spotlight overlay and in Sentry.  Guess I will need to create a minimal reproduce case if no one else is seeing this."_

_Originally posted by @mfb in https://github.com/getsentry/spotlight/issues/275#issuecomment-1933187480_

**Comment by Lms24** [comment] 2024-02-15 09:40
_"@Shubhdeep12 here's a minimal reproduce case for this issue: https://github.com/mfb/spotlight-reproduce

You will need to run `npm install`, make the directory available via a local webserver, start the sidecar service, load index.html in your browser, then click the element to trigger an error."_

Originally posted by @mfb in https://github.com/getsentry/spotlight/issues/275#issuecomment-1936847586

**Comment by Lms24** [comment] 2024-02-15 09:42
Took the liberty to extract this to its own issue since it wasn't directly related to the original issue in #275. 
I also experienced this kinda randomly when clicking on spans in the trace view.

@Shubhdeep12 let's try to fix this. Let me know if the reproduction is enough or if you need more help. Thanks!

**Comment by Shubhdeep12** [comment] 2024-02-15 13:53
Hi @Lms24 
- it would be great if you could also share some more context like a sampled file or something.
- I checked the above reproduction code. it's working fine for me
 https://vimeo.com/913317721/fc71f5b73d
- On looking at the error message, it looks like the issue is with the type of `message` in the event fixed here - https://github.com/getsentry/spotlight/pull/357

**Comment by patelrohan750** [comment] 2024-08-03 06:56
refer to this article to solve the issue [How to Fix “objects are not valid as a react child”](https://reactjsguru.com/objects-are-not-valid-as-a-react-child/)

**Comment by BYK** [comment] 2024-08-05 20:45
Closing per @Shubhdeep12's comment: looks like this was fixed in #357.

**Closed by BYK** 2024-08-05 20:45 UTC
Labels: Type: Bug-confirmed, Package: Overlay
